return {
	["Glass Beetle"] = { LureSpeed = 30, Luck = 125, Rarity = "Rare", GeneralLuck = 0, Resilience = 30 },
	["Worm"] = { LureSpeed = 15, Luck = 25, Rarity = "Common", GeneralLuck = 0, Resilience = 0 },
	["Golden Tentacle"] = { LureSpeed = 50, Luck = 150, Rarity = "Legendary", GeneralLuck = 0, Resilience = 20 },
	["Peppermint Worm"] = { LureSpeed = -5, Luck = 50, Rarity = "Unusual", GeneralLuck = 0, Resilience = 20 },
	["Squid"] = { LureSpeed = -25, Luck = 55, Rarity = "Unusual", GeneralLuck = 0, Resilience = 0 },
	["Fish Head"] = { LureSpeed = 10, Luck = 150, Rarity = "Legendary", GeneralLuck = 0, Resilience = -10 },
	["Ember Berries"] = { LureSpeed = 5, Luck = 120, Rarity = "Unusual", GeneralLuck = 0, Resilience = 15 },
	["Insect"] = { LureSpeed = 5, Luck = 35, Rarity = "Common", GeneralLuck = 0, Resilience = 0 },
	["Crystal Bananas"] = { LureSpeed = 0, Luck = 150, Rarity = "Rare", GeneralLuck = 0, Resilience = 25 },
	["Toxic Jelly Core"] = { LureSpeed = -5, Luck = 180, Rarity = "Legendary", GeneralLuck = 0, Resilience = 35 },
	["Hangman's Hook"] = { LureSpeed = -5, Luck = 150, Rarity = "Mythical", GeneralLuck = 0, Resilience = 20 },
	["Super Flakes"] = { LureSpeed = 0, Luck = 0, Rarity = "Rare", GeneralLuck = 0, Resilience = -15 },
	["Nightmare Larva"] = { LureSpeed = 25, Luck = 120, Rarity = "Mythical", GeneralLuck = 0, Resilience = 25 },
	["Weird Algae"] = { LureSpeed = -35, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0 },
	["Shark Head"] = { LureSpeed = -5, Luck = 225, Rarity = "Mythical", GeneralLuck = 0, Resilience = 10 },
	["Phantom Leech"] = { LureSpeed = 10, Luck = 55, Rarity = "Rare", GeneralLuck = 0, Resilience = 25 },
	["Deep Coral"] = { LureSpeed = 0, Luck = -10, Rarity = "Legendary", GeneralLuck = 0, Resilience = 50 },
	["Aurora Bait"] = { LureSpeed = -5, Luck = 100, Rarity = "Mythical", GeneralLuck = 0, Resilience = 10 },
	["Bagel"] = { LureSpeed = 0, Luck = 25, Rarity = "Common", GeneralLuck = 0, Resilience = 15 },
	["Magnet"] = { LureSpeed = 0, Luck = 200, Rarity = "Unusual", GeneralLuck = 0, Resilience = 0 },
	["Neuro Slug"] = { LureSpeed = -20, Luck = 90, Rarity = "Legendary", GeneralLuck = 0, Resilience = 60 },
	["Coal"] = { LureSpeed = 0, Luck = 45, Rarity = "Rare", GeneralLuck = 0, Resilience = -10 },
	["Shrimp"] = { LureSpeed = 0, Luck = 45, Rarity = "Uncommon", GeneralLuck = 0, Resilience = -5 },
	["Luminous Larva"] = { LureSpeed = 10, Luck = 200, Rarity = "Exotic", GeneralLuck = 0, Resilience = 50 },
	["Coral"] = { LureSpeed = 20, Luck = 0, Rarity = "Unusual", GeneralLuck = 0, Resilience = 20 },
	["Gale Grub"] = { LureSpeed = 30, Luck = 75, Rarity = "Common", GeneralLuck = 0, Resilience = -5 },
	["Sapphire Krill"] = { LureSpeed = 5, Luck = 150, Rarity = "Mythical", GeneralLuck = 0, Resilience = 40 },
	["Chocolate Fish"] = { LureSpeed = 20, Luck = 200, Rarity = "Mythical", GeneralLuck = 0, Resilience = 15 },
	["Night Shrimp"] = { LureSpeed = 15, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0 },
	["Lushrooms"] = { LureSpeed = 10, Luck = 50, Rarity = "Common", GeneralLuck = 0, Resilience = 10 },
	["Instant Catcher"] = { LureSpeed = 65, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = -15 },
	["Golden Worm"] = { LureSpeed = 20, Luck = 200, Rarity = "Exotic", GeneralLuck = 0, Resilience = 45 },
	["Lagoon Leech"] = { LureSpeed = 15, Luck = 65, Rarity = "Rare", GeneralLuck = 0, Resilience = 20 },
	["Kraken Tentacle"] = { LureSpeed = 35, Luck = 100, Rarity = "Legendary", GeneralLuck = 0, Resilience = 15 },
	["Garbage"] = { LureSpeed = -5, Luck = 0, Rarity = "Common", GeneralLuck = 0, Resilience = 50 },
	["Holly Berry"] = { LureSpeed = -5, Luck = 80, Rarity = "Legendary", GeneralLuck = 0, Resilience = 10 },
	["Mist Worms"] = { LureSpeed = 20, Luck = 100, Rarity = "Legendary", GeneralLuck = 0, Resilience = 25 },
	["Rapid Catcher"] = { LureSpeed = 35, Luck = 0, Rarity = "Rare", GeneralLuck = 0, Resilience = -15 },
	["Maggot"] = { LureSpeed = -10, Luck = 0, Rarity = "Uncommon", GeneralLuck = 0, Resilience = 0 },
	["Minnow"] = { LureSpeed = 0, Luck = 65, Rarity = "Unusual", GeneralLuck = 0, Resilience = -10 },
	["Lucky"] = { LureSpeed = 20, Luck = 200, Rarity = "Mythical", GeneralLuck = 0, Resilience = 15 },
	["Flakes"] = { LureSpeed = 10, Luck = 55, Rarity = "Common", GeneralLuck = 0, Resilience = -3 },
	["Seaweed"] = { LureSpeed = 20, Luck = 35, Rarity = "Unusual", GeneralLuck = 0, Resilience = 10 },
	["Truffle Worm"] = { LureSpeed = -10, Luck = 300, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0 },
}
