return {
    ["Magnet"] = {LureSpeed = 0, Luck = 200, Rarity = "Unusual", GeneralLuck = 0, Resilience = 0},
    ["Worm"] = {LureSpeed = 15, Luck = 25, Rarity = "Common", GeneralLuck = 0, Resilience = 0},
    ["Peppermint Worm"] = {LureSpeed = -5, Luck = 50, Rarity = "Unusual", GeneralLuck = 0, Resilience = 20},
    ["Coal"] = {LureSpeed = 0, Luck = 45, Rarity = "Rare", GeneralLuck = 0, Resilience = -10},
    ["Squid"] = {LureSpeed = -25, Luck = 55, Rarity = "Unusual", GeneralLuck = 0, Resilience = 0},
    ["Shrimp"] = {LureSpeed = 0, Luck = 45, Rarity = "Uncommon", GeneralLuck = 0, Resilience = -5},
    ["Kraken Tentacle"] = {LureSpeed = 35, Luck = 100, Rarity = "Legendary", GeneralLuck = 0, Resilience = 15},
    ["Hangman's Hook"] = {LureSpeed = -5, Luck = 150, Rarity = "Mythical", GeneralLuck = 0, Resilience = 20},
    ["Insect"] = {LureSpeed = 5, Luck = 35, Rarity = "Common", GeneralLuck = 0, Resilience = 0},
    ["Night Shrimp"] = {LureSpeed = 15, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0},
    ["Deep Coral"] = {LureSpeed = 0, Luck = -10, Rarity = "Legendary", GeneralLuck = 0, Resilience = 50},
    ["Chocolate Fish"] = {LureSpeed = 20, Luck = 200, Rarity = "Mythical", GeneralLuck = 0, Resilience = 15},
    ["Super Flakes"] = {LureSpeed = 0, Luck = 0, Rarity = "Rare", GeneralLuck = 0, Resilience = -15},
    ["Seaweed"] = {LureSpeed = 20, Luck = 35, Rarity = "Unusual", GeneralLuck = 0, Resilience = 10},
    ["Instant Catcher"] = {LureSpeed = 65, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = -15},
    ["Shark Head"] = {LureSpeed = -5, Luck = 225, Rarity = "Mythical", GeneralLuck = 0, Resilience = 10},
    ["Fish Head"] = {LureSpeed = 10, Luck = 150, Rarity = "Legendary", GeneralLuck = 0, Resilience = -10},
    ["Weird Algae"] = {LureSpeed = -35, Luck = 0, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0},
    ["Garbage"] = {LureSpeed = -5, Luck = 0, Rarity = "Common", GeneralLuck = 0, Resilience = 50},
    ["Holly Berry"] = {LureSpeed = -5, Luck = 80, Rarity = "Legendary", GeneralLuck = 0, Resilience = 10},
    ["Rapid Catcher"] = {LureSpeed = 35, Luck = 0, Rarity = "Rare", GeneralLuck = 0, Resilience = -15},
    ["Minnow"] = {LureSpeed = 0, Luck = 65, Rarity = "Unusual", GeneralLuck = 0, Resilience = -10},
    ["Maggot"] = {LureSpeed = -10, Luck = 0, Rarity = "Uncommon", GeneralLuck = 0, Resilience = 0},
    ["Coral"] = {LureSpeed = 20, Luck = 0, Rarity = "Unusual", GeneralLuck = 0, Resilience = 20},
    ["Flakes"] = {LureSpeed = 10, Luck = 55, Rarity = "Common", GeneralLuck = 0, Resilience = -3},
    ["Aurora Bait"] = {LureSpeed = -5, Luck = 100, Rarity = "Mythical", GeneralLuck = 0, Resilience = 10},
    ["Bagel"] = {LureSpeed = 0, Luck = 25, Rarity = "Common", GeneralLuck = 0, Resilience = 15},
    ["Truffle Worm"] = {LureSpeed = -10, Luck = 300, Rarity = "Legendary", GeneralLuck = 0, Resilience = 0}
}

