
return {
    ["Sand Dollar"] = {FavouriteBait = "None", Rarity = "Common", Price = 20, XP = 35},
    ["Snowcap Algae"] = {FavouriteBait = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Icicle"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 130, XP = 60},
    ["Lingcod"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 110, XP = 80},
    ["Deep Sea Fragment"] = {FavouriteBait = "None", Rarity = "Fragment", Price = 0, XP = 0},
    ["Small Spine Chimera"] = {FavouriteBait = "Seaweed", Rarity = "Legendary", Price = 1200, XP = 300},
    ["Seaweed"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 9, XP = 20},
    ["Napoleonfish"] = {FavouriteBait = "None", Rarity = "Rare", Price = 200, XP = 100},
    ["Philosopher's Fish"] = {FavouriteBait = "Coral", Rarity = "Unusual", Price = 300, XP = 180},
    ["Frozen Fangfish"] = {FavouriteBait = "Shrimp", Rarity = "Limited", Price = 650, XP = 250},
    ["Midnight Axolotl"] = {FavouriteBait = "Insect", Rarity = "Legendary", Price = 1100, XP = 550},
    ["Trout"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 65, XP = 40},
    ["Rabbitfish"] = {FavouriteBait = "Seaweed", Rarity = "Legendary", Price = 1100, XP = 800},
    ["Moonstone"] = {FavouriteBait = "None", Rarity = "Gemstone", Price = 1000, XP = 200},
    ["Captain's Goldfish"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 1700, XP = 2800},
    ["Typhoon Tuna"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 900, XP = 450},
    ["Largemouth Bass"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 85, XP = 20},
    ["Baby Pond Emperor"] = {FavouriteBait = "Squid", Rarity = "Secret", Price = 5000, XP = 100},
    ["Walleye"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 90, XP = 90},
    ["Brine Phantom"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Sturgeon"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 300, XP = 100},
    ["Arctic Char"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 80, XP = 50},
    ["Oarfish"] = {FavouriteBait = "Squid", Rarity = "Mythical", Price = 4000, XP = 2000},
    ["Lobster"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 130, XP = 60},
    ["Frigid Mammoth Tusk"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 3000, XP = 1200},
    ["Starfish"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 110, XP = 115},
    ["Pollock"] = {FavouriteBait = "None", Rarity = "Common", Price = 70, XP = 50},
    ["Mushgrove Algae"] = {FavouriteBait = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Molten Minnow"] = {FavouriteBait = "Flakes", Rarity = "Limited", Price = 400, XP = 180},
    ["Moon Wood"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 450, XP = 50},
    ["Void Wood"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 350, XP = 35},
    ["Banditfish"] = {FavouriteBait = "Insect", Rarity = "Rare", Price = 250, XP = 100},
    ["Leviathan Bass"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 400, XP = 200},
    ["Twilight Tentaclefish"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 13000, XP = 3400},
    ["Typhoon Tailfin"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 9000, XP = 2800},
    ["Siren Sculpin"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 4000, XP = 1450},
    ["Icy Carp"] = {FavouriteBait = "Bagel", Rarity = "Unusual", Price = 250, XP = 120},
    ["Turkey"] = {FavouriteBait = "Insect", Rarity = "Limited", Price = 4000, XP = 1700},
    ["Gorgon Grouper"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 1500, XP = 1350},
    ["Volcanic Geode"] = {FavouriteBait = "Magnet", Rarity = "Rare", Price = 200, XP = 20},
    ["Swordfish"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 850, XP = 300},
    ["Grand Reef Guardian"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 7000, XP = 3500},
    ["Serpent Surgeonfish"] = {FavouriteBait = "Bagel", Rarity = "Uncommon", Price = 1250, XP = 220},
    ["Cockatoo Squid"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 200, XP = 65},
    ["Galleon Goliath"] = {FavouriteBait = "Squid", Rarity = "Uncommon", Price = 190, XP = 85},
    ["Destroyed Fossil"] = {FavouriteBait = "None", Rarity = "Trash", Price = 35, XP = 20},
    ["Prismatic Parrotfish"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 1500, XP = 650},
    ["Lurkerfish"] = {FavouriteBait = "Squid", Rarity = "Limited", Price = 1500, XP = 800},
    ["Hydra Haddock"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 400, XP = 160},
    ["Blisterback Blenny"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 6300, XP = 1500},
    ["Crystal Corydoras"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 3000, XP = 2000},
    ["Atlantean Sardine"] = {FavouriteBait = "None", Rarity = "Common", Price = 35, XP = 20},
    ["Colossal Saccopharynx"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 100, XP = 90},
    ["Hallucigenia"] = {FavouriteBait = "Flakes", Rarity = "Rare", Price = 200, XP = 125},
    ["Bone"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 30, XP = 25},
    ["Meg's Fang"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 1500, XP = 250},
    ["Nessie"] = {FavouriteBait = "Truffle Worm", Rarity = "Limited", Price = 6500, XP = 3000},
    ["Frozen Walnut"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 2500, XP = 700},
    ["Molten Moray"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 1300, XP = 450},
    ["Vortex Barracuda"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 600, XP = 300},
    ["Skipjack Tuna"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 150, XP = 100},
    ["Pyrite Pufferfish"] = {FavouriteBait = "Shrimp", Rarity = "Rare", Price = 1100, XP = 250},
    ["Atlantean Guardian"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 250, XP = 150},
    ["Smoldering Stingray"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 900, XP = 150},
    ["Voidfin Mahi"] = {FavouriteBait = "Truffle Worm", Rarity = "Rare", Price = 450, XP = 400},
    ["Pyro Pike"] = {FavouriteBait = "Shrimp", Rarity = "Limited", Price = 500, XP = 240},
    ["Voltfin Carp"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 180, XP = 100},
    ["Diamond Discus"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 1200, XP = 110},
    ["Hellfire Haddock"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 50, XP = 20},
    ["Helicoprion"] = {FavouriteBait = "Squid", Rarity = "Mythical", Price = 6000, XP = 2500},
    ["Inferno Hide"] = {FavouriteBait = "None", Rarity = "Common", Price = 50, XP = 250},
    ["Porgy"] = {FavouriteBait = "Shrimp", Rarity = "Common", Price = 90, XP = 40},
    ["Shimmering Silverside"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 7800, XP = 2400},
    ["Buccaneer Barracuda"] = {FavouriteBait = "Deep Coral", Rarity = "Uncommon", Price = 250, XP = 100},
    ["Ruby Rasbora"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 1400, XP = 350},
    ["Cryoskin"] = {FavouriteBait = "None", Rarity = "Common", Price = 50, XP = 250},
    ["Icy Walleye"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 350, XP = 160},
    ["Emerald Elephantnose"] = {FavouriteBait = "Bagel", Rarity = "Uncommon", Price = 1000, XP = 100},
    ["Embertail Eel"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 130, XP = 90},
    ["Boot"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 15, XP = 20},
    ["Megalodon"] = {FavouriteBait = "Shark Head", Rarity = "Exotic", Price = 10000, XP = 6000},
    ["Quartzfin Queenfish"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 300, XP = 50},
    ["Bluefin Tuna"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 350, XP = 120},
    ["Giant Seadevil"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 9000, XP = 3800},
    ["Long Pike"] = {FavouriteBait = "Insect", Rarity = "Secret", Price = 18000, XP = 6600},
    ["Infant Giant Seadevil"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 5000, XP = 2600},
    ["Yellow Energy Crystal"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 0, XP = 250},
    ["Maelstorm Shark"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Spectral Serpent"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 9000, XP = 3500},
    ["Bowfin"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 100, XP = 50},
    ["Mackerel"] = {FavouriteBait = "Shrimp", Rarity = "Common", Price = 75, XP = 80},
    ["Anglers Lantern"] = {FavouriteBait = "None", Rarity = "Exotic", Price = 1200, XP = 350},
    ["Stingray"] = {FavouriteBait = "None", Rarity = "Rare", Price = 230, XP = 100},
    ["Mahi Mahi"] = {FavouriteBait = "None", Rarity = "Rare", Price = 150, XP = 90},
    ["Radiant Triplewart Seadevil"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 600, XP = 200},
    ["Abyssal Bearded Seadevil"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 120, XP = 95},
    ["Leviathan Humpback Anglerfish"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 40, XP = 25},
    ["Minnow"] = {FavouriteBait = "Bagel", Rarity = "Common", Price = 45, XP = 75},
    ["Ember Catfish"] = {FavouriteBait = "Bagel", Rarity = "Limited", Price = 275, XP = 130},
    ["Titanic Black Seadevil"] = {FavouriteBait = "Bagel", Rarity = "Common", Price = 45, XP = 20},
    ["Thunder Bass"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 450, XP = 250},
    ["Moby"] = {FavouriteBait = "Squid", Rarity = "Secret", Price = 75000, XP = 60000},
    ["Polar Alligator"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Olmdeer"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 400, XP = 300},
    ["Tentacled Horror"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 300, XP = 180},
    ["Blue Whale"] = {FavouriteBait = "Shrimp", Rarity = "Exotic", Price = 30000, XP = 25000},
    ["Phanerorhynchus"] = {FavouriteBait = "Deep Coral", Rarity = "Rare", Price = 450, XP = 90},
    ["Ancient Orca"] = {FavouriteBait = "Shark Head", Rarity = "Secret", Price = 15000, XP = 10000},
    ["Mutated Shark"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 3000, XP = 800},
    ["Gudgeon"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 40, XP = 10},
    ["Orca"] = {FavouriteBait = "Shark Head", Rarity = "Exotic", Price = 12000, XP = 8000},
    ["Ancient Serpent Skull"] = {FavouriteBait = "None", Rarity = "Limited", Price = 1200, XP = 400},
    ["Goblin Shark"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 450, XP = 80},
    ["Coral Guard"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 250, XP = 180},
    ["Golden Smallmouth Bass"] = {FavouriteBait = "Flakes", Rarity = "Legendary", Price = 700, XP = 250},
    ["The Kraken"] = {FavouriteBait = "Truffle Worm", Rarity = "Exotic", Price = 20000, XP = 10000},
    ["Abyssal Devourer"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 8000, XP = 4000},
    ["Void Emperor"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 6000, XP = 3000},
    ["Reef Minnow"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 85, XP = 65},
    ["Icebeard Shark"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 8000, XP = 2500},
    ["Abyssal King"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 4000, XP = 2000},
    ["Twilight Eel"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 90, XP = 100},
    ["Eldritch Horror"] = {FavouriteBait = "Truffle Worm", Rarity = "Rare", Price = 1200, XP = 600},
    ["Abyssacuda"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 400, XP = 90},
    ["Zeus' Herald"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 5000, XP = 2000},
    ["Tentacle Eel"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 450, XP = 250},
    ["Chillfin Chimaera"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 4000, XP = 2800},
    ["Diplurus"] = {FavouriteBait = "Shrimp", Rarity = "Legendary", Price = 800, XP = 250},
    ["Ancient Wood"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 450, XP = 50},
    ["Cookie"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 20, XP = 9},
    ["Cookiecutter Shark"] = {FavouriteBait = "Bagel", Rarity = "Rare", Price = 500, XP = 300},
    ["Crab"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 100, XP = 50},
    ["Solar Fragment"] = {FavouriteBait = "None", Rarity = "Fragment", Price = 50, XP = 10},
    ["Icy Goldfish"] = {FavouriteBait = "Flakes", Rarity = "Rare", Price = 800, XP = 300},
    ["Scooty Salmon"] = {FavouriteBait = "Seaweed", Rarity = "Limited", Price = 750, XP = 350},
    ["King Jellyfish"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 3500, XP = 1800},
    ["Grey Carp"] = {FavouriteBait = "Seaweed", Rarity = "Uncommon", Price = 120, XP = 75},
    ["Frostling Goby"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Three-eyed Fish"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 200, XP = 55},
    ["Snowflake Smelt"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Log"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 124, XP = 45},
    ["Starlit Weaver"] = {FavouriteBait = "Deep Coral", Rarity = "Rare", Price = 800, XP = 500},
    ["Voidscale Guppy"] = {FavouriteBait = "Night Shrimp", Rarity = "Rare", Price = 650, XP = 400},
    ["Molten Banshee"] = {FavouriteBait = "Truffle Worm", Rarity = "Exotic", Price = 6500, XP = 2000},
    ["Prawn"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 45, XP = 35},
    ["Lovestorm Eel"] = {FavouriteBait = "Chocolate Fish", Rarity = "Secret", Price = 15000, XP = 10000},
    ["Snook"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 110, XP = 45},
    ["Siren Singer"] = {FavouriteBait = "Deep Coral", Rarity = "Unusual", Price = 380, XP = 220},
    ["Oracle's Eye"] = {FavouriteBait = "Night Shrimp", Rarity = "Unusual", Price = 350, XP = 200},
    ["Echo Fisher"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 190, XP = 115},
    ["Tidal Pike"] = {FavouriteBait = "Night Shrimp", Rarity = "Limited", Price = 1500, XP = 800},
    ["Frost Minnow"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 150, XP = 85},
    ["Spider Crab"] = {FavouriteBait = "Deep Coral", Rarity = "Rare", Price = 550, XP = 135},
    ["Crystallized Seadragon"] = {FavouriteBait = "Shark Head", Rarity = "Secret", Price = 35000, XP = 40000},
    ["Deep Crownfish"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 2000, XP = 1000},
    ["Red Snapper"] = {FavouriteBait = "None", Rarity = "Common", Price = 70, XP = 80},
    ["Temple Drifter"] = {FavouriteBait = "Deep Coral", Rarity = "Uncommon", Price = 170, XP = 105},
    ["Lava Lamprey"] = {FavouriteBait = "Insect", Rarity = "Limited", Price = 350, XP = 170},
    ["Massive Marlin"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 800, XP = 400},
    ["Salmon"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 130, XP = 90},
    ["Glass Diamond"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 1500, XP = 250},
    ["Magma Leviathan"] = {FavouriteBait = "Truffle Worm", Rarity = "Secret", Price = 25000, XP = 12000},
    ["Triton's Herald"] = {FavouriteBait = "Deep Coral", Rarity = "Rare", Price = 500, XP = 300},
    ["Aqua Scribe"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 60, XP = 40},
    ["Glacier Swordfish"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 1000, XP = 400},
    ["Neptune's Nibbler"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 45, XP = 30},
    ["Column Crawler"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 55, XP = 35},
    ["Amblypterus"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 2500, XP = 700},
    ["Mustard"] = {FavouriteBait = "Seaweed", Rarity = "Secret", Price = 19000, XP = 7000},
    ["Cobia"] = {FavouriteBait = "Insect", Rarity = "Rare", Price = 230, XP = 140},
    ["Confetti Shark"] = {FavouriteBait = "Deep Coral", Rarity = "Limited", Price = 1200, XP = 600},
    ["Scylla"] = {FavouriteBait = "Shark Head", Rarity = "Secret", Price = 200000, XP = 500000},
    ["Crystal Wrasse"] = {FavouriteBait = "Insect", Rarity = "Unusual", Price = 450, XP = 300},
    ["Hollyscale Trout"] = {FavouriteBait = "Insect", Rarity = "Limited", Price = 150, XP = 50},
    ["Magma Tang"] = {FavouriteBait = "Coal", Rarity = "Uncommon", Price = 130, XP = 90},
    ["Redeye Bass"] = {FavouriteBait = "Flakes", Rarity = "Unusual", Price = 115, XP = 100},
    ["Carp"] = {FavouriteBait = "Bagel", Rarity = "Uncommon", Price = 110, XP = 80},
    ["Celestial Koi"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 8000, XP = 3000},
    ["Countdown Perch"] = {FavouriteBait = "Weird Algae", Rarity = "Limited", Price = 2000, XP = 1200},
    ["Hyneria"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 145, XP = 120},
    ["Ghoulfish"] = {FavouriteBait = "Squid", Rarity = "Limited", Price = 1000, XP = 600},
    ["Mosasaurus"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 7500, XP = 3000},
    ["Sailfish"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 800, XP = 300},
    ["Helios Ray"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 180, XP = 110},
    ["Hollow Flake Catfish"] = {FavouriteBait = "Squid", Rarity = "Limited", Price = 450, XP = 135},
    ["Icebreaker Haddock"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 800, XP = 350},
    ["Pyrogrub"] = {FavouriteBait = "Coal", Rarity = "Rare", Price = 340, XP = 120},
    ["Sea Snake"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 5000, XP = 1200},
    ["Marble Maiden"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 120, XP = 80},
    ["Poseidon's Perch"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 70, XP = 50},
    ["Oracle Minnow"] = {FavouriteBait = "Flakes", Rarity = "Common", Price = 50, XP = 30},
    ["Cursed Eel"] = {FavouriteBait = "Coal", Rarity = "Rare", Price = 700, XP = 250},
    ["Atlantean Anchovy"] = {FavouriteBait = "None", Rarity = "Common", Price = 40, XP = 25},
    ["Sunken Silverscale"] = {FavouriteBait = "Shrimp", Rarity = "Common", Price = 65, XP = 45},
    ["Grayling"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 80, XP = 100},
    ["Lapis Lazuli"] = {FavouriteBait = "None", Rarity = "Gemstone", Price = 700, XP = 150},
    ["Abyssal Goliath"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 6000, XP = 2500},
    ["Deep Behemoth"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 4000, XP = 2000},
    ["Static Ray"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 280, XP = 150},
    ["Golden Seahorse"] = {FavouriteBait = "Weird Algae", Rarity = "Mythical", Price = 2900, XP = 2800},
    ["Mythic Fish"] = {FavouriteBait = "Flakes", Rarity = "Mythical", Price = 2000, XP = 800},
    ["Deep Emperor"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Sardine"] = {FavouriteBait = "None", Rarity = "Common", Price = 30, XP = 20},
    ["Lapisjack"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 115, XP = 80},
    ["Clownfish"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 90, XP = 90},
    ["Mullet"] = {FavouriteBait = "Bagel", Rarity = "Common", Price = 90, XP = 40},
    ["Frostscale Fangtooth"] = {FavouriteBait = "Bagel", Rarity = "Common", Price = 30, XP = 50},
    ["Whisker Bill"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 3100, XP = 1000},
    ["Burbot"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 80, XP = 110},
    ["Titanic Sturgeon"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 900, XP = 450},
    ["Snowback Char"] = {FavouriteBait = "Insect", Rarity = "Unusual", Price = 320, XP = 150},
    ["Fish Barrel"] = {FavouriteBait = "Magnet", Rarity = "Uncommon", Price = 80, XP = 40},
    ["Flying Fish"] = {FavouriteBait = "Minnow", Rarity = "Legendary", Price = 1200, XP = 700},
    ["Giant Manta"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 350, XP = 180},
    ["Voltfish"] = {FavouriteBait = "Super Flakes", Rarity = "Mythical", Price = 2200, XP = 850},
    ["Coral Geode"] = {FavouriteBait = "Magnet", Rarity = "Uncommon", Price = 200, XP = 20},
    ["Amberjack"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 115, XP = 80},
    ["Colossal Carp"] = {FavouriteBait = "Seaweed", Rarity = "Uncommon", Price = 180, XP = 100},
    ["Deep One"] = {FavouriteBait = "Truffle Worm", Rarity = "Rare", Price = 900, XP = 400},
    ["Polar Prowler"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 1500, XP = 2000},
    ["Alligator Gar"] = {FavouriteBait = "None", Rarity = "Rare", Price = 220, XP = 100},
    ["Xiphactinus"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 170, XP = 135},
    ["Yellowfin Tuna"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 120, XP = 80},
    ["Stormcloud Angelfish"] = {FavouriteBait = "Shrimp", Rarity = "Rare", Price = 310, XP = 231},
    ["Scurvy Sailfish"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 300, XP = 140},
    ["Mauve Pearl"] = {FavouriteBait = "None", Rarity = "Rare", Price = 200, XP = 0},
    ["Sparkfin Tetra"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 90, XP = 30},
    ["Lightning Pike"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 276, XP = 143},
    ["Barracuda's Spine"] = {FavouriteBait = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Sea Turtle"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 2000, XP = 1000},
    ["Storm Eel"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 550, XP = 300},
    ["Lightning Minnow"] = {FavouriteBait = "Flakes", Rarity = "Common", Price = 120, XP = 80},
    ["Cinder Carp"] = {FavouriteBait = "Minnow", Rarity = "Limited", Price = 600, XP = 275},
    ["Iceberg Isopod"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 400, XP = 350},
    ["Frozen Leviathan"] = {FavouriteBait = "Truffle Worm", Rarity = "Secret", Price = 18000, XP = 20000},
    ["Emperor Jellyfish"] = {FavouriteBait = "Magnet", Rarity = "Mythical", Price = 6000, XP = 4500},
    ["Shiverfin Haddock"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 500, XP = 220},
    ["Angelfish"] = {FavouriteBait = "Worm", Rarity = "Unusual", Price = 120, XP = 60},
    ["Nautilus"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 1000, XP = 300},
    ["Oyster"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 30, XP = 35},
    ["Chillshadow Chub"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 100, XP = 100},
    ["Subzero Stargazer"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 100, XP = 110},
    ["Sapphire Stargazer"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 1300, XP = 250},
    ["Ruby"] = {FavouriteBait = "None", Rarity = "Gemstone", Price = 200, XP = 70},
    ["Earth Fragment"] = {FavouriteBait = "None", Rarity = "Fragment", Price = 0, XP = 0},
    ["Smallmouth Bass"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 70, XP = 90},
    ["Eternal Frostwhale"] = {FavouriteBait = "Shark Head", Rarity = "Limited", Price = 12000, XP = 8000},
    ["Hourglass Bass"] = {FavouriteBait = "Aurora Bait", Rarity = "Limited", Price = 3000, XP = 2000},
    ["Shark Fang"] = {FavouriteBait = "None", Rarity = "Limited", Price = 135, XP = 50},
    ["Red Energy Crystal"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 5, XP = 250},
    ["Atlantean Alchemist"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 800, XP = 500},
    ["Enchant Relic"] = {FavouriteBait = "None", Rarity = "Relic", Price = 3500, XP = 800},
    ["Chub"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 40, XP = 40},
    ["Deep Freeze Devilfish"] = {FavouriteBait = "Squid", Rarity = "Unusual", Price = 300, XP = 250},
    ["Ornament Fish"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 140, XP = 165},
    ["Chronos Deep Swimmer"] = {FavouriteBait = "Truffle Worm", Rarity = "Unusual", Price = 400, XP = 240},
    ["Resin"] = {FavouriteBait = "None", Rarity = "Secret", Price = 800, XP = 250},
    ["Crystal Carp"] = {FavouriteBait = "Maggot", Rarity = "Limited", Price = 375, XP = 90},
    ["Santa Salmon"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 120, XP = 130},
    ["Onychodus"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 115, XP = 110},
    ["Swamp Bass"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 60, XP = 50},
    ["Glass of Milk"] = {FavouriteBait = "Peppermint Worm", Rarity = "Limited", Price = 20, XP = 9},
    ["Festive Bait Crate"] = {FavouriteBait = "Magnet", Rarity = "Limited", Price = 500, XP = 300},
    ["Floppy"] = {FavouriteBait = "Super Flakes", Rarity = "Legendary", Price = 2000, XP = 1200},
    ["Chillback Whitefish"] = {FavouriteBait = "Worm", Rarity = "Unusual", Price = 280, XP = 130},
    ["Trumpetfish"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 100, XP = 80},
    ["Sawfish"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 1500, XP = 900},
    ["Rock"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 15, XP = 10},
    ["Mussel"] = {FavouriteBait = "None", Rarity = "Common", Price = 20, XP = 35},
    ["Common Crate"] = {FavouriteBait = "Magnet", Rarity = "Uncommon", Price = 80, XP = 20},
    ["Banana"] = {FavouriteBait = "None", Rarity = "Secret", Price = 18500, XP = 6900},
    ["Nurse Shark"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 200, XP = 100},
    ["Cyclone Scorpionfish"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 1800, XP = 1150},
    ["Brine Shrimp"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 230, XP = 130},
    ["Scalding Swordfish"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 4000, XP = 1100},
    ["Skelefish"] = {FavouriteBait = "Fish Head", Rarity = "Limited", Price = 200, XP = 400},
    ["Globe Jellyfish"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 300, XP = 150},
    ["Coelacanth"] = {FavouriteBait = "None", Rarity = "Rare", Price = 370, XP = 300},
    ["Candy Fish"] = {FavouriteBait = "Flakes", Rarity = "Limited", Price = 200, XP = 400},
    ["Meg's Spine"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 1500, XP = 250},
    ["Crystal Chorus"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 160, XP = 100},
    ["Chinfish"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 85, XP = 40},
    ["Chillfin Herring"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 450, XP = 200},
    ["Infernal Iguanafish"] = {FavouriteBait = "Insect", Rarity = "Uncommon", Price = 120, XP = 80},
    ["Phantom Megalodon"] = {FavouriteBait = "Shark Head", Rarity = "Limited", Price = 20000, XP = 12000},
    ["Icy Tuna"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 600, XP = 250},
    ["Bull Shark"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 400, XP = 150},
    ["Kraken's Herald"] = {FavouriteBait = "Truffle Worm", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Ice Jellyfish"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 280, XP = 130},
    ["Night Shrimp"] = {FavouriteBait = "None", Rarity = "Common", Price = 55, XP = 35},
    ["Ancient Algae"] = {FavouriteBait = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Manta Ray"] = {FavouriteBait = "Shrimp", Rarity = "Mythical", Price = 3000, XP = 1000},
    ["Ancient Megalodon"] = {FavouriteBait = "Shark Head", Rarity = "Exotic", Price = 16000, XP = 9000},
    ["Thunder Serpent"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 2500, XP = 1200},
    ["Olm"] = {FavouriteBait = "Flakes", Rarity = "Legendary", Price = 900, XP = 500},
    ["Driftwood"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 10, XP = 30},
    ["Black Dragon Fish"] = {FavouriteBait = "Deep Coral", Rarity = "Rare", Price = 500, XP = 120},
    ["Pumpkinseed"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 90, XP = 30},
    ["King Oyster"] = {FavouriteBait = "None", Rarity = "Rare", Price = 200, XP = 35},
    ["Chinook Salmon"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 230, XP = 100},
    ["Barracuda"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 150, XP = 90},
    ["Snowfish"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 800, XP = 300},
    ["Perch"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 70, XP = 80},
    ["Glacier Glowfish"] = {FavouriteBait = "Shrimp", Rarity = "Limited", Price = 1800, XP = 450},
    ["Titan Tuna"] = {FavouriteBait = "Fish Head", Rarity = "Uncommon", Price = 220, XP = 120},
    ["Stalactite"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 35, XP = 20},
    ["Arapaima"] = {FavouriteBait = "Minnow", Rarity = "Rare", Price = 250, XP = 150},
    ["Sunfish"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 1500, XP = 550},
    ["Deeplight Footballfish"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 1000, XP = 325},
    ["Supreme Present"] = {FavouriteBait = "Magnet", Rarity = "Limited", Price = 650, XP = 120},
    ["Reef Parrotfish"] = {FavouriteBait = "Coral", Rarity = "Rare", Price = 900, XP = 600},
    ["Forsaken Algae"] = {FavouriteBait = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Ancient Serpent Spine"] = {FavouriteBait = "None", Rarity = "Limited", Price = 800, XP = 250},
    ["Longtail Bass"] = {FavouriteBait = "Shrimp", Rarity = "Uncommon", Price = 120, XP = 70},
    ["White Perch"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 80, XP = 80},
    ["Goldfish"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 65, XP = 75},
    ["Exalted Relic"] = {FavouriteBait = "None", Rarity = "Relic", Price = 12000, XP = 2500},
    ["Sweetfish"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 40, XP = 25},
    ["Ancient Kraken"] = {FavouriteBait = "Truffle Worm", Rarity = "Secret", Price = 50000, XP = 25000},
    ["Ringle"] = {FavouriteBait = "Bagel", Rarity = "Mythical", Price = 900, XP = 500},
    ["Mushgrove Crab"] = {FavouriteBait = "None", Rarity = "Rare", Price = 330, XP = 80},
    ["Zombiefish"] = {FavouriteBait = "Flakes", Rarity = "Limited", Price = 200, XP = 400},
    ["Acanthodii"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 160, XP = 130},
    ["Phantom Ray"] = {FavouriteBait = "Weird Algae", Rarity = "Uncommon", Price = 140, XP = 60},
    ["Glacier Pike"] = {FavouriteBait = "Insect", Rarity = "Unusual", Price = 230, XP = 90},
    ["Frigid Taco"] = {FavouriteBait = "None", Rarity = "Rare", Price = 600, XP = 250},
    ["Scrap Metal"] = {FavouriteBait = "None", Rarity = "Trash", Price = 40, XP = 20},
    ["Frozen Pike"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 650, XP = 280},
    ["Blackfish"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 100, XP = 100},
    ["Crowned Anglerfish"] = {FavouriteBait = "Truffle Worm", Rarity = "Secret", Price = 22000, XP = 16000},
    ["Reef Goby"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 200, XP = 150},
    ["Tempest Ray"] = {FavouriteBait = "Seaweed", Rarity = "Uncommon", Price = 250, XP = 150},
    ["Aurora Trout"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 6000, XP = 2000},
    ["Bluegill"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 60, XP = 90},
    ["Eel"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 130, XP = 90},
    ["Spiderfish"] = {FavouriteBait = "None", Rarity = "Common", Price = 30, XP = 20},
    ["Butterflyfish"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 110, XP = 60},
    ["Eyefestation"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Ancient Fragment"] = {FavouriteBait = "None", Rarity = "Fragment", Price = 500, XP = 80},
    ["Gingerbread Fish"] = {FavouriteBait = "Peppermint Worm", Rarity = "Limited", Price = 135, XP = 150},
    ["Barreleye Fish"] = {FavouriteBait = "Deep Coral", Rarity = "Mythical", Price = 4500, XP = 950},
    ["Carbon Crate"] = {FavouriteBait = "Magnet", Rarity = "Rare", Price = 140, XP = 50},
    ["Coral Chromis"] = {FavouriteBait = "Flakes", Rarity = "Common", Price = 120, XP = 95},
    ["Shadowfang Snapper"] = {FavouriteBait = "Fish Head", Rarity = "Uncommon", Price = 200, XP = 120},
    ["Obsidian Salmon"] = {FavouriteBait = "Coal", Rarity = "Legendary", Price = 600, XP = 300},
    ["Depth Octopus"] = {FavouriteBait = "Coral", Rarity = "Unusual", Price = 175, XP = 50},
    ["Nessie's Spine"] = {FavouriteBait = "None", Rarity = "Limited", Price = 250, XP = 90},
    ["Isonade"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 8000, XP = 1200},
    ["Ribbon Eel"] = {FavouriteBait = "Minnow", Rarity = "Unusual", Price = 150, XP = 150},
    ["Clam"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 13, XP = 25},
    ["Sea Urchin"] = {FavouriteBait = "None", Rarity = "Rare", Price = 320, XP = 80},
    ["Green Energy Crystal"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 0, XP = 250},
    ["Ember Snapper"] = {FavouriteBait = "Coal", Rarity = "Unusual", Price = 200, XP = 120},
    ["Frostbite Flounder"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 750, XP = 300},
    ["Frigid Antlers"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 1200, XP = 800},
    ["Fossil Fan"] = {FavouriteBait = "None", Rarity = "Limited", Price = 60, XP = 22},
    ["Kraken Koi"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 1100, XP = 330},
    ["Ancient Eel"] = {FavouriteBait = "Coal", Rarity = "Legendary", Price = 1500, XP = 350},
    ["Golden Sea Pearl"] = {FavouriteBait = "None", Rarity = "Exotic", Price = 3500, XP = 600},
    ["Aurora Pearl"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 2250, XP = 0},
    ["Ice"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 15, XP = 10},
    ["Spine Bone"] = {FavouriteBait = "None", Rarity = "Limited", Price = 80, XP = 35},
    ["Birgeria"] = {FavouriteBait = "Worm", Rarity = "Unusual", Price = 200, XP = 60},
    ["Ginsu Shark"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3000, XP = 1800},
    ["Shipwreck Barracuda"] = {FavouriteBait = "Coral", Rarity = "Legendary", Price = 1200, XP = 400},
    ["Frilled Shark"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 150, XP = 45},
    ["Rockstar Hermit Crab"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 65, XP = 75},
    ["Deep Pearl"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 880, XP = 0},
    ["Swamp Scallop"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 150, XP = 40},
    ["Icefang Barracuda"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 650, XP = 300},
    ["Axolotl"] = {FavouriteBait = "Insect", Rarity = "Legendary", Price = 1000, XP = 550},
    ["Dumbo Octopus"] = {FavouriteBait = "Worm", Rarity = "Legendary", Price = 900, XP = 400},
    ["Marsh Gar"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 280, XP = 100},
    ["Barbed Shark"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 8300, XP = 4000},
    ["Scallop"] = {FavouriteBait = "None", Rarity = "Uncommon", Price = 100, XP = 40},
    ["Cladoselache"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 90, XP = 95},
    ["Piranha"] = {FavouriteBait = "Squid", Rarity = "Common", Price = 85, XP = 95},
    ["Deep-sea Dragonfish"] = {FavouriteBait = "Deep Coral", Rarity = "Common", Price = 45, XP = 25},
    ["Luminescent Minnow"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 120, XP = 30},
    ["Frostjaw Cod"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 2000, XP = 800},
    ["Wiifish"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 1200, XP = 500},
    ["Treble Bass"] = {FavouriteBait = "Magnet", Rarity = "Exotic", Price = 4000, XP = 1200},
    ["Rose Pearl"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 145, XP = 0},
    ["Yellow Boxfish"] = {FavouriteBait = "Seaweed", Rarity = "Unusual", Price = 140, XP = 100},
    ["Cyclone Mako"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 1200, XP = 600},
    ["Haddock"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 50, XP = 60},
    ["Palaeoniscum"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 125, XP = 35},
    ["Squid"] = {FavouriteBait = "Shrimp", Rarity = "Unusual", Price = 140, XP = 95},
    ["Gilded Pearl"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 120, XP = 0},
    ["Blue Tang"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 90, XP = 90},
    ["Titanfang Grouper"] = {FavouriteBait = "Fish Head", Rarity = "Rare", Price = 1000, XP = 500},
    ["Dunkleosteus"] = {FavouriteBait = "Minnow", Rarity = "Legendary", Price = 3500, XP = 2000},
    ["Lovestorm Eel Supercharged"] = {FavouriteBait = "Chocolate Fish", Rarity = "Secret", Price = 25000, XP = 20000},
    ["Dolphin"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 1200, XP = 600},
    ["Alligator"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 700, XP = 400},
    ["White Bass"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 110, XP = 50},
    ["Santa Pufferfish"] = {FavouriteBait = "Peppermint Worm", Rarity = "Limited", Price = 2000, XP = 1200},
    ["Whale Shark"] = {FavouriteBait = "Shrimp", Rarity = "Mythical", Price = 6500, XP = 3000},
    ["Blistered Eel"] = {FavouriteBait = "Worm", Rarity = "Limited", Price = 300, XP = 140},
    ["Ancient Depth Serpent"] = {FavouriteBait = "Truffle Worm", Rarity = "Exotic", Price = 8000, XP = 2200},
    ["Shortfin Mako Shark"] = {FavouriteBait = "Deep Coral", Rarity = "Common", Price = 190, XP = 70},
    ["Sea Pickle"] = {FavouriteBait = "Seaweed", Rarity = "Mythical", Price = 2000, XP = 60},
    ["Great Hammerhead Shark"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 5500, XP = 860},
    ["Great White Shark"] = {FavouriteBait = "Fish Head", Rarity = "Mythical", Price = 6000, XP = 900},
    ["Amethyst"] = {FavouriteBait = "None", Rarity = "Gemstone", Price = 150, XP = 35},
    ["Bait Crate"] = {FavouriteBait = "Magnet", Rarity = "Uncommon", Price = 75, XP = 40},
    ["Crown Bass"] = {FavouriteBait = "Squid", Rarity = "Legendary", Price = 1200, XP = 700},
    ["Moonfish"] = {FavouriteBait = "Minnow", Rarity = "Legendary", Price = 1800, XP = 900},
    ["Tire"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 20, XP = 10},
    ["Fangborn Gar"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 170, XP = 100},
    ["Obsidian Swordfish"] = {FavouriteBait = "Minnow", Rarity = "Mythical", Price = 2500, XP = 1000},
    ["Opal"] = {FavouriteBait = "None", Rarity = "Gemstone", Price = 500, XP = 115},
    ["Twilight Glowfish"] = {FavouriteBait = "Night Shrimp", Rarity = "Rare", Price = 650, XP = 400},
    ["Basic Present"] = {FavouriteBait = "Magnet", Rarity = "Limited", Price = 120, XP = 40},
    ["Anglerfish"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 230, XP = 100},
    ["Ember Perch"] = {FavouriteBait = "None", Rarity = "Unusual", Price = 160, XP = 100},
    ["Cutlass Fish"] = {FavouriteBait = "Worm", Rarity = "Unusual", Price = 500, XP = 175},
    ["Halibut"] = {FavouriteBait = "Squid", Rarity = "Rare", Price = 250, XP = 100},
    ["Anomalocaris"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 90, XP = 100},
    ["Pike"] = {FavouriteBait = "Insect", Rarity = "Unusual", Price = 230, XP = 90},
    ["Pond Emperor"] = {FavouriteBait = "Squid", Rarity = "Legendary", Price = 900, XP = 700},
    ["Pufferfish"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 230, XP = 100},
    ["Cod"] = {FavouriteBait = "Minnow", Rarity = "Uncommon", Price = 90, XP = 70},
    ["Sea Mine"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 3000, XP = 1000},
    ["Shrimp"] = {FavouriteBait = "None", Rarity = "Common", Price = 45, XP = 35},
    ["Sea Bass"] = {FavouriteBait = "Squid", Rarity = "Common", Price = 95, XP = 90},
    ["Sockeye Salmon"] = {FavouriteBait = "Bagel", Rarity = "Common", Price = 45, XP = 25},
    ["Basalt"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 15, XP = 10},
    ["Pearl"] = {FavouriteBait = "None", Rarity = "Common", Price = 60, XP = 0},
    ["Void Angler"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 4500, XP = 2000},
    ["Catfish"] = {FavouriteBait = "Worm", Rarity = "Rare", Price = 300, XP = 120},
    ["Suckermouth Catfish"] = {FavouriteBait = "Seaweed", Rarity = "Rare", Price = 160, XP = 80},
    ["Spined Fin"] = {FavouriteBait = "None", Rarity = "Limited", Price = 300, XP = 120},
    ["Mage Marlin"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 2500, XP = 1200},
    ["Voidglow Ghostfish"] = {FavouriteBait = "Squid", Rarity = "Legendary", Price = 7500, XP = 2800},
    ["Glassfish"] = {FavouriteBait = "Flakes", Rarity = "Common", Price = 45, XP = 50},
    ["Deep-sea Hatchetfish"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 35, XP = 20},
    ["Pale Tang"] = {FavouriteBait = "Bagel", Rarity = "Uncommon", Price = 100, XP = 90},
    ["Whiptail Catfish"] = {FavouriteBait = "Seaweed", Rarity = "Legendary", Price = 600, XP = 200},
    ["Flounder"] = {FavouriteBait = "Squid", Rarity = "Unusual", Price = 120, XP = 80},
    ["Bream"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 60, XP = 30},
    ["Anchovy"] = {FavouriteBait = "None", Rarity = "Common", Price = 30, XP = 20},
    ["Mosaic Swimmer"] = {FavouriteBait = "Coral", Rarity = "Uncommon", Price = 150, XP = 95},
    ["Umbral Shark"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 1000, XP = 500},
    ["Keepers Guardian"] = {FavouriteBait = "Worm", Rarity = "Rare", Price = 250, XP = 120},
    ["Bluefish"] = {FavouriteBait = "Flakes", Rarity = "Unusual", Price = 65, XP = 75},
    ["Fungal Cluster"] = {FavouriteBait = "Magnet", Rarity = "Trash", Price = 9, XP = 20},
    ["Herring"] = {FavouriteBait = "Shrimp", Rarity = "Common", Price = 70, XP = 50},
    ["Slate Tuna"] = {FavouriteBait = "Super Flakes", Rarity = "Common", Price = 70, XP = 25},
    ["Horseshoe Crab"] = {FavouriteBait = "None", Rarity = "Common", Price = 25, XP = 60},
    ["Dweller Catfish"] = {FavouriteBait = "Weird Algae", Rarity = "Rare", Price = 440, XP = 150},
    ["Gazerfish"] = {FavouriteBait = "Worm", Rarity = "Common", Price = 190, XP = 100},
    ["Burnt Betta"] = {FavouriteBait = "Squid", Rarity = "Limited", Price = 3000, XP = 1500},
    ["Song of the Deep"] = {FavouriteBait = "None", Rarity = "Relic", Price = 1200, XP = 250},
    ["Northstar Serpent"] = {FavouriteBait = "Holly Berry", Rarity = "Limited", Price = 20000, XP = 5000},
    ["Glacial Sturgeon"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 7000, XP = 2200},
    ["Inferno Wood"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 700, XP = 90},
    ["Unique Present"] = {FavouriteBait = "Magnet", Rarity = "Limited", Price = 180, XP = 55},
    ["Leedsichthys"] = {FavouriteBait = "Squid", Rarity = "Legendary", Price = 2200, XP = 1500},
    ["Red Tang"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 100, XP = 90},
    ["Candy Cane Carp"] = {FavouriteBait = "Peppermint Worm", Rarity = "Limited", Price = 75, XP = 85},
    ["Reefrunner Snapper"] = {FavouriteBait = "Insect", Rarity = "Rare", Price = 750, XP = 200},
    ["Corsair Grouper"] = {FavouriteBait = "Seaweed", Rarity = "Common", Price = 35, XP = 30},
    ["Claw Gill"] = {FavouriteBait = "None", Rarity = "Limited", Price = 60, XP = 22},
    ["Colossal Squid"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 6500, XP = 3000},
    ["Icy Salmon"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Handfish"] = {FavouriteBait = "Insect", Rarity = "Mythical", Price = 1000, XP = 500},
    ["Blue Energy Crystal"] = {FavouriteBait = "None", Rarity = "Mythical", Price = 0, XP = 250},
    ["Snowflake Flounder"] = {FavouriteBait = "Peppermint Worm", Rarity = "Limited", Price = 145, XP = 180},
    ["Red Drum"] = {FavouriteBait = "Insect", Rarity = "Common", Price = 80, XP = 50},
    ["Snowgill Dace"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 160, XP = 90},
    ["Frigid Crab"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 300, XP = 140},
    ["Lepidotes"] = {FavouriteBait = "Deep Coral", Rarity = "Mythical", Price = 1800, XP = 500},
    ["Frigid Shrimp"] = {FavouriteBait = "Flakes", Rarity = "Uncommon", Price = 175, XP = 90},
    ["Glacierfish"] = {FavouriteBait = "Truffle Worm", Rarity = "Mythical", Price = 800, XP = 400},
    ["Cryo Coelacanth"] = {FavouriteBait = "Shrimp", Rarity = "Rare", Price = 500, XP = 650},
    ["Borealis Snapper"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 3500, XP = 1200},
    ["Whirlpool Marlin"] = {FavouriteBait = "Squid", Rarity = "Unusual", Price = 450, XP = 250},
    ["Spine Blade"] = {FavouriteBait = "None", Rarity = "Limited", Price = 100, XP = 40},
    ["Quality Bait Crate"] = {FavouriteBait = "Magnet", Rarity = "Rare", Price = 150, XP = 40},
    ["The Depths Key"] = {FavouriteBait = "None", Rarity = "Exotic", Price = 800, XP = 350},
    ["Rubber Ducky"] = {FavouriteBait = "None", Rarity = "Legendary", Price = 900, XP = 800},
    ["Ashcloud Archerfish"] = {FavouriteBait = "Coal", Rarity = "Limited", Price = 24000, XP = 6000},
    ["Ice Eel"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 155, XP = 95},
    ["Abyss Snapper"] = {FavouriteBait = "Fish Head", Rarity = "Uncommon", Price = 300, XP = 180},
    ["Iced Perch"] = {FavouriteBait = "Insect", Rarity = "Unusual", Price = 250, XP = 120},
    ["Ice Octopus"] = {FavouriteBait = "Fish Head", Rarity = "Unusual", Price = 350, XP = 150},
    ["Ice Anchovy"] = {FavouriteBait = "Worm", Rarity = "Uncommon", Price = 140, XP = 80},
    ["Coral Emperor"] = {FavouriteBait = "Fish Head", Rarity = "Legendary", Price = 4000, XP = 1800}
}
