local fish = {
    ["Snowcap Algae"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Lingcod"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Unusual", Price = 110, XP = 80},
    ["Deep Sea Fragment"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Fragment", Price = 0, XP = 0},
    ["Small Spine Chimera"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Legendary", Price = 1200, XP = 300},
    ["Napoleonfish"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Rare", Price = 200, XP = 100},
    ["Philosopher's Fish"] = {FavouriteBait = "Coral", FavouriteTime = "Day", Rarity = "Unusual", Price = 300, XP = 180},
    ["Frozen Fangfish"] = {FavouriteBait = "Shrimp", FavouriteTime = "None", Rarity = "Legendary", Price = 650, XP = 250},
    ["Midnight Axolotl"] = {FavouriteBait = "Insect", FavouriteTime = "Night", Rarity = "Legendary", Price = 1100, XP = 550},
    ["Captain's Goldfish"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Day", Rarity = "Mythical", Price = 1700, XP = 2800},
    ["Typhoon Tuna"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 900, XP = 450},
    ["Brine Phantom"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Frigid Mammoth Tusk"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Mythical", Price = 3000, XP = 1200},
    ["Mushgrove Algae"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Aurora Trout"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 6000, XP = 2000},
    ["Icy Carp"] = {FavouriteBait = "Bagel", FavouriteTime = "None", Rarity = "Unusual", Price = 250, XP = 120},
    ["Grand Reef Guardian"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "None", Rarity = "Mythical", Price = 7000, XP = 3500},
    ["Cockatoo Squid"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Unusual", Price = 200, XP = 65},
    ["Galleon Goliath"] = {FavouriteBait = "Squid", FavouriteTime = "Day", Rarity = "Uncommon", Price = 190, XP = 85},
    ["Destroyed Fossil"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Trash", Price = 35, XP = 20},
    ["Palaeoniscus"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 125, XP = 35},
    ["Atlantean Sardine"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Common", Price = 35, XP = 20},
    ["Hallucigenia"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Rare", Price = 200, XP = 125},
    ["Frozen Walnut"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Mythical", Price = 2500, XP = 700},
    ["Vortex Barracuda"] = {FavouriteBait = "Minnow", FavouriteTime = "None", Rarity = "Unusual", Price = 600, XP = 300},
    ["Porgy"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Common", Price = 90, XP = 40},
    ["Buccaneer Barracuda"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Uncommon", Price = 250, XP = 100},
    ["Icy Walleye"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Unusual", Price = 350, XP = 160},
    ["Megalodon"] = {FavouriteBait = "Shark Head", FavouriteTime = "None", Rarity = "Exotic", Price = 10000, XP = 6000},
    ["Maelstorm Shark"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "None", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Spectral Serpent"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 9000, XP = 3500},
    ["Mackerel"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Common", Price = 75, XP = 80},
    ["Oracle's Eye"] = {FavouriteBait = "Night Shrimp", FavouriteTime = "Night", Rarity = "Unusual", Price = 350, XP = 200},
    ["Stingray"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Rare", Price = 230, XP = 100},
    ["Thunder Bass"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 450, XP = 250},
    ["Polar Alligator"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Olmdeer"] = {FavouriteBait = "Holly Berry", FavouriteTime = "Night", Rarity = "Limited", Price = 400, XP = 300},
    ["Tentacled Horror"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Uncommon", Price = 300, XP = 180},
    ["Phanerorhynchus"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Rare", Price = 450, XP = 90},
    ["Mutated Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Mythical", Price = 3000, XP = 800},
    ["Gudgeon"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Common", Price = 40, XP = 10},
    ["Goblin Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Rare", Price = 450, XP = 80},
    ["Coral Guard"] = {FavouriteBait = "Shrimp", FavouriteTime = "None", Rarity = "Uncommon", Price = 250, XP = 180},
    ["Golden Smallmouth Bass"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Legendary", Price = 700, XP = 250},
    ["Reef Minnow"] = {FavouriteBait = "Seaweed", FavouriteTime = "None", Rarity = "Common", Price = 85, XP = 65},
    ["Icebeard Shark"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 8000, XP = 2500},
    ["Diplurus"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Legendary", Price = 800, XP = 250},
    ["Solar Fragment"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Fragment", Price = 50, XP = 10},
    ["Icy Goldfish"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Rare", Price = 800, XP = 300},
    ["Glacial Sturgeon"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 7000, XP = 2200},
    ["Frostling Goby"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Three-eyed Fish"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Unusual", Price = 200, XP = 55},
    ["Snowflake Smelt"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Prawn"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Uncommon", Price = 45, XP = 35},
    ["Frost Minnow"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Uncommon", Price = 150, XP = 85},
    ["Spider Crab"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Day", Rarity = "Rare", Price = 550, XP = 135},
    ["Deep Crownfish"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Legendary", Price = 2000, XP = 1000},
    ["Massive Marlin"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Rare", Price = 800, XP = 400},
    ["Triton's Herald"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Rare", Price = 500, XP = 300},
    ["Glacier Swordfish"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 1000, XP = 400},
    ["Amblypterus"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Mythical", Price = 2500, XP = 700},
    ["Crystal Wrasse"] = {FavouriteBait = "Insect", FavouriteTime = "None", Rarity = "Unusual", Price = 450, XP = 300},
    ["Hollyscale Trout"] = {FavouriteBait = "Insect", FavouriteTime = "None", Rarity = "Unusual", Price = 150, XP = 50},
    ["Magma Tang"] = {FavouriteBait = "Coal", FavouriteTime = "Day", Rarity = "Uncommon", Price = 130, XP = 90},
    ["Redeye Bass"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Unusual", Price = 115, XP = 100},
    ["The Kraken"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Exotic", Price = 20000, XP = 10000},
    ["Abyssal Devourer"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 8000, XP = 4000},
    ["Mosasaurus"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 7500, XP = 3000},
    ["Void Emperor"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 6000, XP = 3000},
    ["Abyssal King"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Legendary", Price = 4000, XP = 2000},
    ["Hollow Flake Catfish"] = {FavouriteBait = "Squid", FavouriteTime = "None", Rarity = "Rare", Price = 450, XP = 135},
    ["Icebreaker Haddock"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Rare", Price = 800, XP = 350},
    ["Sea Snake"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Mythical", Price = 5000, XP = 1200},
    ["Eldritch Horror"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Rare", Price = 1200, XP = 600},
    ["Tentacle Eel"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 450, XP = 250},
    ["Cursed Eel"] = {FavouriteBait = "Coal", FavouriteTime = "Night", Rarity = "Rare", Price = 700, XP = 250},
    ["Cookiecutter Shark"] = {FavouriteBait = "Bagel", FavouriteTime = "Night", Rarity = "Rare", Price = 500, XP = 300},
    ["King Jellyfish"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 3500, XP = 1800},
    ["Grayling"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Common", Price = 80, XP = 100},
    ["Shrimp"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Common", Price = 45, XP = 35},
    ["Starlit Weaver"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Rare", Price = 800, XP = 500},
    ["Golden Seahorse"] = {FavouriteBait = "Weird Algae", FavouriteTime = "Day", Rarity = "Mythical", Price = 2900, XP = 2800},
    ["Mythic Fish"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Mythical", Price = 2000, XP = 800},
    ["Voidscale Guppy"] = {FavouriteBait = "Night Shrimp", FavouriteTime = "Night", Rarity = "Rare", Price = 650, XP = 400},
    ["Sardine"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Common", Price = 30, XP = 20},
    ["Lapisjack"] = {FavouriteBait = "Minnow", FavouriteTime = "Day", Rarity = "Rare", Price = 115, XP = 80},
    ["Siren Singer"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Unusual", Price = 380, XP = 220},
    ["Echo Fisher"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Uncommon", Price = 190, XP = 115},
    ["Snowback Char"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Unusual", Price = 320, XP = 150},
    ["Flying Fish"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Legendary", Price = 1200, XP = 700},
    ["Temple Drifter"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Day", Rarity = "Uncommon", Price = 170, XP = 105},
    ["Borealis Snapper"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3500, XP = 1200},
    ["Amberjack"] = {FavouriteBait = "Minnow", FavouriteTime = "Day", Rarity = "Uncommon", Price = 115, XP = 80},
    ["Neptune's Nibbler"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Common", Price = 45, XP = 30},
    ["Deep One"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Rare", Price = 900, XP = 400},
    ["Celestial Koi"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 8000, XP = 3000},
    ["Xiphactinus"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 170, XP = 135},
    ["Onychodus"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Uncommon", Price = 115, XP = 110},
    ["Scurvy Sailfish"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Unusual", Price = 300, XP = 140},
    ["Great Hammerhead Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Mythical", Price = 5500, XP = 860},
    ["Helios Ray"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Unusual", Price = 180, XP = 110},
    ["Barracuda's Spine"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Poseidon's Perch"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Common", Price = 70, XP = 50},
    ["Oracle Minnow"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Common", Price = 50, XP = 30},
    ["Ancient Serpent Skull"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 1200, XP = 400},
    ["Sunken Silverscale"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Common", Price = 65, XP = 45},
    ["Deep Behemoth"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Legendary", Price = 4000, XP = 2000},
    ["Deep Emperor"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Titanic Sturgeon"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Rare", Price = 900, XP = 450},
    ["Earth Fragment"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Fragment", Price = 0, XP = 0},
    ["Leviathan Bass"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 400, XP = 200},
    ["Giant Manta"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Unusual", Price = 350, XP = 180},
    ["Shark Fang"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 135, XP = 50},
    ["Atlantean Alchemist"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Rare", Price = 800, XP = 500},
    ["Colossal Carp"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Uncommon", Price = 180, XP = 100},
    ["Zeus' Herald"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Mythical", Price = 5000, XP = 2000},
    ["Sparkfin Tetra"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Common", Price = 90, XP = 30},
    ["Resin"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Secret", Price = 800, XP = 250},
    ["Crystal Carp"] = {FavouriteBait = "Maggot", FavouriteTime = "None", Rarity = "Unusual", Price = 375, XP = 90},
    ["Storm Eel"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 550, XP = 300},
    ["Lightning Minnow"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Common", Price = 120, XP = 80},
    ["Chillback Whitefish"] = {FavouriteBait = "Worm", FavouriteTime = "None", Rarity = "Unusual", Price = 280, XP = 130},
    ["Trumpetfish"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Unusual", Price = 100, XP = 80},
    ["Sawfish"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 1500, XP = 900},
    ["Yellow Boxfish"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Unusual", Price = 140, XP = 100},
    ["Corsair Grouper"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Common", Price = 35, XP = 30},
    ["Brine Shrimp"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Uncommon", Price = 230, XP = 130},
    ["Ringle"] = {FavouriteBait = "Bagel", FavouriteTime = "Night", Rarity = "Mythical", Price = 900, XP = 500},
    ["Crystal Chorus"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Uncommon", Price = 160, XP = 100},
    ["Sea Turtle"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Mythical", Price = 2000, XP = 1000},
    ["Phantom Megalodon"] = {FavouriteBait = "Shark Head", FavouriteTime = "None", Rarity = "Limited", Price = 20000, XP = 12000},
    ["Icy Tuna"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 600, XP = 250},
    ["Gazerfish"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Common", Price = 190, XP = 100},
    ["Kraken's Herald"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1500},
    ["Ice Jellyfish"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Unusual", Price = 280, XP = 130},
    ["Nessie"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Limited", Price = 6500, XP = 3000},
    ["Ancient Algae"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Ancient Megalodon"] = {FavouriteBait = "Shark Head", FavouriteTime = "None", Rarity = "Exotic", Price = 16000, XP = 9000},
    ["Thunder Serpent"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Legendary", Price = 2500, XP = 1200},
    ["Black Dragon Fish"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Rare", Price = 500, XP = 120},
    ["Blackfish"] = {FavouriteBait = "Worm", FavouriteTime = "Night", Rarity = "Uncommon", Price = 100, XP = 100},
    ["Shiverfin Haddock"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Rare", Price = 500, XP = 220},
    ["Barracuda"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Uncommon", Price = 150, XP = 90},
    ["Snowfish"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 800, XP = 300},
    ["Glacier Glowfish"] = {FavouriteBait = "Shrimp", FavouriteTime = "None", Rarity = "Mythical", Price = 1800, XP = 450},
    ["Titan Tuna"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Uncommon", Price = 220, XP = 120},
    ["Night Shrimp"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Common", Price = 55, XP = 35},
    ["Nautilus"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Legendary", Price = 1000, XP = 300},
    ["Reef Parrotfish"] = {FavouriteBait = "Coral", FavouriteTime = "None", Rarity = "Rare", Price = 900, XP = 600},
    ["Forsaken Algae"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 50, XP = 20},
    ["Ancient Serpent Spine"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 800, XP = 250},
    ["Olm"] = {FavouriteBait = "Flakes", FavouriteTime = "Night", Rarity = "Legendary", Price = 900, XP = 500},
    ["Goldfish"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Uncommon", Price = 65, XP = 75},
    ["Ancient Kraken"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Secret", Price = 50000, XP = 25000},
    ["Voltfish"] = {FavouriteBait = "Super Flakes", FavouriteTime = "Night", Rarity = "Mythical", Price = 2200, XP = 850},
    ["Phantom Ray"] = {FavouriteBait = "Weird Algae", FavouriteTime = "Night", Rarity = "Uncommon", Price = 140, XP = 60},
    ["Sunfish"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Legendary", Price = 1500, XP = 550},
    ["Frigid Taco"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Rare", Price = 600, XP = 250},
    ["Scrap Metal"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Trash", Price = 40, XP = 20},
    ["Frozen Pike"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 650, XP = 280},
    ["Reef Goby"] = {FavouriteBait = "Worm", FavouriteTime = "None", Rarity = "Uncommon", Price = 200, XP = 150},
    ["Tempest Ray"] = {FavouriteBait = "Seaweed", FavouriteTime = "None", Rarity = "Uncommon", Price = 250, XP = 150},
    ["Reefrunner Snapper"] = {FavouriteBait = "Insect", FavouriteTime = "Day", Rarity = "Rare", Price = 750, XP = 200},
    ["Eel"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Unusual", Price = 130, XP = 90},
    ["Butterflyfish"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Uncommon", Price = 110, XP = 60},
    ["Eyefestation"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1000},
    ["Ancient Fragment"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Fragment", Price = 500, XP = 80},
    ["Barreleye Fish"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Mythical", Price = 4500, XP = 950},
    ["Coral Chromis"] = {FavouriteBait = "Flakes", FavouriteTime = "None", Rarity = "Common", Price = 120, XP = 95},
    ["Shadowfang Snapper"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Uncommon", Price = 200, XP = 120},
    ["Depth Octopus"] = {FavouriteBait = "Coral", FavouriteTime = "Day", Rarity = "Unusual", Price = 175, XP = 50},
    ["Nessie's Spine"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 250, XP = 90},
    ["Anchovy"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Common", Price = 30, XP = 20},
    ["Ancient Depth Serpent"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Exotic", Price = 8000, XP = 2200},
    ["Frostbite Flounder"] = {FavouriteBait = "Squid", FavouriteTime = "None", Rarity = "Rare", Price = 750, XP = 300},
    ["Frigid Antlers"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Legendary", Price = 1200, XP = 800},
    ["Fossil Fan"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 60, XP = 22},
    ["Obsidian Salmon"] = {FavouriteBait = "Coal", FavouriteTime = "Night", Rarity = "Legendary", Price = 600, XP = 300},
    ["Sea Pickle"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Mythical", Price = 2000, XP = 60},
    ["Spine Bone"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 80, XP = 35},
    ["Birgeria"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Unusual", Price = 200, XP = 60},
    ["Ginsu Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 3000, XP = 1800},
    ["Shipwreck Barracuda"] = {FavouriteBait = "Coral", FavouriteTime = "Night", Rarity = "Legendary", Price = 1200, XP = 400},
    ["Frilled Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Unusual", Price = 150, XP = 45},
    ["Icefang Barracuda"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 650, XP = 300},
    ["Moonfish"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Legendary", Price = 1800, XP = 900},
    ["Cladoselache"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Common", Price = 90, XP = 95},
    ["Deep-sea Dragonfish"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Common", Price = 45, XP = 25},
    ["Luminescent Minnow"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Unusual", Price = 120, XP = 30},
    ["Frostjaw Cod"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 2000, XP = 800},
    ["Cyclone Mako"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Rare", Price = 1200, XP = 600},
    ["Haddock"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Common", Price = 50, XP = 60},
    ["Manta Ray"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Mythical", Price = 3000, XP = 1000},
    ["Axolotl"] = {FavouriteBait = "Insect", FavouriteTime = "Night", Rarity = "Legendary", Price = 1000, XP = 550},
    ["Titanfang Grouper"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Rare", Price = 1000, XP = 500},
    ["Dunkleosteus"] = {FavouriteBait = "Minnow", FavouriteTime = "Day", Rarity = "Legendary", Price = 3500, XP = 2000},
    ["Dolphin"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Legendary", Price = 1200, XP = 600},
    ["White Bass"] = {FavouriteBait = "Minnow", FavouriteTime = "Day", Rarity = "Uncommon", Price = 110, XP = 50},
    ["Santa Pufferfish"] = {FavouriteBait = "Peppermint Worm", FavouriteTime = "Night", Rarity = "Limited", Price = 2000, XP = 1200},
    ["Squid"] = {FavouriteBait = "Shrimp", FavouriteTime = "Night", Rarity = "Unusual", Price = 140, XP = 95},
    ["Blue Tang"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Uncommon", Price = 90, XP = 90},
    ["Shortfin Mako Shark"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Common", Price = 190, XP = 70},
    ["Coelacanth"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Rare", Price = 370, XP = 300},
    ["Chub"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Common", Price = 40, XP = 40},
    ["Whale Shark"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Mythical", Price = 6500, XP = 3000},
    ["Twilight Glowfish"] = {FavouriteBait = "Night Shrimp", FavouriteTime = "Night", Rarity = "Rare", Price = 650, XP = 400},
    ["Crown Bass"] = {FavouriteBait = "Squid", FavouriteTime = "Night", Rarity = "Legendary", Price = 1200, XP = 700},
    ["Cutlass Fish"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Unusual", Price = 500, XP = 175},
    ["Anomalocaris"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Uncommon", Price = 90, XP = 100},
    ["Anglerfish"] = {FavouriteBait = "Squid", FavouriteTime = "Night", Rarity = "Rare", Price = 230, XP = 100},
    ["Void Angler"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "None", Rarity = "Mythical", Price = 4500, XP = 2000},
    ["Nurse Shark"] = {FavouriteBait = "Minnow", FavouriteTime = "Night", Rarity = "Unusual", Price = 200, XP = 100},
    ["Suckermouth Catfish"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Rare", Price = 160, XP = 80},
    ["Spined Fin"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 300, XP = 120},
    ["Mage Marlin"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 2500, XP = 1200},
    ["Deep-sea Hatchetfish"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Common", Price = 35, XP = 20},
    ["Alligator"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 700, XP = 400},
    ["Catfish"] = {FavouriteBait = "Worm", FavouriteTime = "Night", Rarity = "Rare", Price = 300, XP = 120},
    ["Chillfin Herring"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Rare", Price = 450, XP = 200},
    ["Bowfin"] = {FavouriteBait = "Worm", FavouriteTime = "Night", Rarity = "Uncommon", Price = 100, XP = 50},
    ["Bream"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Common", Price = 60, XP = 30},
    ["Whiptail Catfish"] = {FavouriteBait = "Seaweed", FavouriteTime = "Night", Rarity = "Legendary", Price = 600, XP = 200},
    ["Flounder"] = {FavouriteBait = "Squid", FavouriteTime = "Night", Rarity = "Unusual", Price = 120, XP = 80},
    ["Herring"] = {FavouriteBait = "Shrimp", FavouriteTime = "Day", Rarity = "Common", Price = 70, XP = 50},
    ["Umbral Shark"] = {FavouriteBait = "Fish Head", FavouriteTime = "Night", Rarity = "Legendary", Price = 1000, XP = 500},
    ["Bluefish"] = {FavouriteBait = "Flakes", FavouriteTime = "Day", Rarity = "Unusual", Price = 65, XP = 75},
    ["Abyssal Goliath"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 6000, XP = 2500},
    ["Northstar Serpent"] = {FavouriteBait = "Holly Berry", FavouriteTime = "None", Rarity = "Limited", Price = 20000, XP = 5000},
    ["Dweller Catfish"] = {FavouriteBait = "Weird Algae", FavouriteTime = "Day", Rarity = "Rare", Price = 440, XP = 150},
    ["Candy Cane Carp"] = {FavouriteBait = "Peppermint Worm", FavouriteTime = "Day", Rarity = "Limited", Price = 75, XP = 85},
    ["Leedsichthys"] = {FavouriteBait = "Squid", FavouriteTime = "Day", Rarity = "Legendary", Price = 2200, XP = 1500},
    ["Claw Gill"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 60, XP = 22},
    ["Colossal Squid"] = {FavouriteBait = "None", FavouriteTime = "Night", Rarity = "Mythical", Price = 6500, XP = 3000},
    ["Icy Salmon"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Uncommon", Price = 180, XP = 95},
    ["Snowflake Flounder"] = {FavouriteBait = "Peppermint Worm", FavouriteTime = "Night", Rarity = "Limited", Price = 145, XP = 180},
    ["Snowgill Dace"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Uncommon", Price = 160, XP = 90},
    ["Frigid Crab"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Unusual", Price = 300, XP = 140},
    ["Ancient Eel"] = {FavouriteBait = "Coal", FavouriteTime = "Night", Rarity = "Legendary", Price = 1500, XP = 350},
    ["Frigid Shrimp"] = {FavouriteBait = "Flakes", FavouriteTime = "Night", Rarity = "Uncommon", Price = 175, XP = 90},
    ["Glacierfish"] = {FavouriteBait = "Truffle Worm", FavouriteTime = "Night", Rarity = "Mythical", Price = 800, XP = 400},
    ["Aqua Scribe"] = {FavouriteBait = "Seaweed", FavouriteTime = "Day", Rarity = "Common", Price = 60, XP = 40},
    ["Lepidotes"] = {FavouriteBait = "Deep Coral", FavouriteTime = "Night", Rarity = "Mythical", Price = 1800, XP = 500},
    ["Whirlpool Marlin"] = {FavouriteBait = "Squid", FavouriteTime = "None", Rarity = "Unusual", Price = 450, XP = 250},
    ["Spine Blade"] = {FavouriteBait = "None", FavouriteTime = "None", Rarity = "Limited", Price = 100, XP = 40},
    ["The Depths Key"] = {FavouriteBait = "None", FavouriteTime = "Day", Rarity = "Exotic", Price = 800, XP = 350},
    ["Ice Eel"] = {FavouriteBait = "Worm", FavouriteTime = "Night", Rarity = "Uncommon", Price = 155, XP = 95},
    ["Abyss Snapper"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Uncommon", Price = 300, XP = 180},
    ["Iced Perch"] = {FavouriteBait = "Insect", FavouriteTime = "None", Rarity = "Unusual", Price = 250, XP = 120},
    ["Ice Octopus"] = {FavouriteBait = "Fish Head", FavouriteTime = "Day", Rarity = "Unusual", Price = 350, XP = 150},
    ["Ice Anchovy"] = {FavouriteBait = "Worm", FavouriteTime = "Day", Rarity = "Uncommon", Price = 140, XP = 80},
    ["Coral Emperor"] = {FavouriteBait = "Fish Head", FavouriteTime = "None", Rarity = "Legendary", Price = 4000, XP = 1800}
}
