return {
    ["Blessed"] = {PriceMultiply = 10},
    ["Electric Shock"] = {PriceMultiply = 3.5},
    ["Silver"] = {PriceMultiply = 1.6},
    ["Mosaic"] = {PriceMultiply = 1.5},
    ["Jolly"] = {PriceMultiply = 1.2},
    ["Celestial"] = {PriceMultiply = 2},
    ["Scorched"] = {PriceMultiply = 1.3},
    ["Fossilized"] = {PriceMultiply = 2.5},
    ["Albino"] = {PriceMultiply = 1.1},
    ["Abyssal"] = {PriceMultiply = 1},
    ["Aurora"] = {PriceMultiply = 6.5},
    ["Darkened"] = {PriceMultiply = 1.3},
    ["Tentacle Surge"] = {PriceMultiply = 10},
    ["Kingâ€™s Blessing"] = {PriceMultiply = 1.5},
    ["Hexed"] = {PriceMultiply = 1.5},
    ["Charred"] = {PriceMultiply = 0.5},
    ["Studded"] = {PriceMultiply = 1.1},
    ["Blighted"] = {PriceMultiply = 3},
    ["Aureate"] = {PriceMultiply = 4},
    ["Electric"] = {PriceMultiply = 1.45},
    ["Chocolate"] = {PriceMultiply = 2.5},
    ["Amber"] = {PriceMultiply = 0.5},
    ["Lightning"] = {PriceMultiply = 1},
    ["Mila's Magic"] = {PriceMultiply = 2.5},
    ["Frozen"] = {PriceMultiply = 1.3},
    ["Firework"] = {PriceMultiply = 3.5},
    ["Aurous"] = {PriceMultiply = 2},
    ["Minty"] = {PriceMultiply = 2.2},
    ["Mythical"] = {PriceMultiply = 4.5},
    ["Anomalous"] = {PriceMultiply = 2.5},
    ["Sandy"] = {PriceMultiply = 1.2},
    ["Festive"] = {PriceMultiply = 1.4},
    ["Heavenly"] = {PriceMultiply = 5},
    ["Unsellable"] = {PriceMultiply = 0},
    ["Atlantean"] = {PriceMultiply = 3},
    ["Glossy"] = {PriceMultiply = 1.6},
    ["Subspace"] = {PriceMultiply = 5},
    ["Midas"] = {PriceMultiply = 2},
    ["Translucent"] = {PriceMultiply = 1.3},
    ["Sinister"] = {PriceMultiply = 1.9},
    ["Lunar"] = {PriceMultiply = 2.5},
    ["Nuclear"] = {PriceMultiply = 4},
    ["Aureolin"] = {PriceMultiply = 5},
    ["Seasonal"] = {PriceMultiply = 1.3},
    ["Negative"] = {PriceMultiply = 1.3},
    ["Aurulent"] = {PriceMultiply = 5},
    ["Aurelian"] = {PriceMultiply = 3},
    ["Revitalized"] = {PriceMultiply = 4},
    ["Purified"] = {PriceMultiply = 2},
    ["Sunken"] = {PriceMultiply = 4},
    ["Crystalized"] = {PriceMultiply = 1.75},
    ["Wrath"] = {PriceMultiply = 6.5},
    ["Doomsday"] = {PriceMultiply = 4},
    ["Sleet"] = {PriceMultiply = 2.4},
    ["Solarblaze"] = {PriceMultiply = 2.5},
    ["Greedy"] = {PriceMultiply = 4},
    ["Ghastly"] = {PriceMultiply = 2}
}
