return {
	["Electric Shock"] = { PriceMultiply = 3.5 },
	["Chocolate"] = { PriceMultiply = 2.5 },
	["Scorched"] = { PriceMultiply = 2.5 },
	["Aurulent"] = { PriceMultiply = 3.5 },
	["Mother Nature"] = { PriceMultiply = 3 },
	["Albino"] = { PriceMultiply = 1.1 },
	["Aurora"] = { PriceMultiply = 6.5 },
	["Darkened"] = { PriceMultiply = 1.3 },
	["Brother"] = { PriceMultiply = 1.5 },
	["Chaotic"] = { PriceMultiply = 12 },
	["Blighted"] = { PriceMultiply = 3 },
	["Minty"] = { PriceMultiply = 2.2 },
	["Cursed Touch"] = { PriceMultiply = 5 },
	["Green"] = { PriceMultiply = 1 },
	["Cracked"] = { PriceMultiply = 3 },
	["Sanguine"] = { PriceMultiply = 8 },
	["Colossal Ink"] = { PriceMultiply = 5 },
	["Mythical"] = { PriceMultiply = 4.5 },
	["Emberflame"] = { PriceMultiply = 5 },
	["Atlantean"] = { PriceMultiply = 3 },
	["Glossy"] = { PriceMultiply = 1.6 },
	["Lost"] = { PriceMultiply = 5.5 },
	["Translucent"] = { PriceMultiply = 1.3 },
	["Brown Wood"] = { PriceMultiply = 3 },
	["Seasonal"] = { PriceMultiply = 1.3 },
	["Negative"] = { PriceMultiply = 1.3 },
	["Ashen Fortune"] = { PriceMultiply = 5 },
	["Sunken"] = { PriceMultiply = 4 },
	["Crystalized"] = { PriceMultiply = 3 },
	["Wrath"] = { PriceMultiply = 6.5 },
	["Doomsday"] = { PriceMultiply = 4 },
	["Solarblaze"] = { PriceMultiply = 2.5 },
	["Ember"] = { PriceMultiply = 3 },
	["LEGO"] = { PriceMultiply = 3 },
	["Mosaic"] = { PriceMultiply = 1.5 },
	["Jolly"] = { PriceMultiply = 1.2 },
	["Celestial"] = { PriceMultiply = 3 },
	["Fossilized"] = { PriceMultiply = 2.5 },
	["Abyssal"] = { PriceMultiply = 1 },
	["Blue"] = { PriceMultiply = 1 },
	["Tentacle Surge"] = { PriceMultiply = 10 },
	["Lightning"] = { PriceMultiply = 1 },
	["Kingâ€™s Blessing"] = { PriceMultiply = 3.5 },
	["Charred"] = { PriceMultiply = 0.5 },
	["Studded"] = { PriceMultiply = 1.1 },
	["Pink"] = { PriceMultiply = 1 },
	["Aureate"] = { PriceMultiply = 3 },
	["Red"] = { PriceMultiply = 1 },
	["Mila's Magic"] = { PriceMultiply = 2.5 },
	["Bloom"] = { PriceMultiply = 5 },
	["Easter"] = { PriceMultiply = 4 },
	["Clover"] = { PriceMultiply = 4.5 },
	["Frozen"] = { PriceMultiply = 1.3 },
	["Green Leaf"] = { PriceMultiply = 3 },
	["Aurous"] = { PriceMultiply = 2 },
	["Neon"] = { PriceMultiply = 5 },
	["Firework"] = { PriceMultiply = 3.5 },
	["Anomalous"] = { PriceMultiply = 4.44 },
	["Sandy"] = { PriceMultiply = 1.2 },
	["Purified"] = { PriceMultiply = 2 },
	["Blarney"] = { PriceMultiply = 4.5 },
	["Aurelian"] = { PriceMultiply = 2.5 },
	["Subspace"] = { PriceMultiply = 5 },
	["Unsellable"] = { PriceMultiply = 0 },
	["Blessed"] = { PriceMultiply = 10 },
	["Midas"] = { PriceMultiply = 2 },
	["Revitalized"] = { PriceMultiply = 4 },
	["Sinister"] = { PriceMultiply = 1.9 },
	["Lunar"] = { PriceMultiply = 2.5 },
	["Female"] = { PriceMultiply = 1 },
	["Cursed"] = { PriceMultiply = 1 },
	["Aureolin"] = { PriceMultiply = 4 },
	["Festive"] = { PriceMultiply = 1.4 },
	["Amber"] = { PriceMultiply = 0.5 },
	["Prismize"] = { PriceMultiply = 8 },
	["Moon-Kissed"] = { PriceMultiply = 2.2 },
	["Hexed"] = { PriceMultiply = 1.5 },
	["Nuclear"] = { PriceMultiply = 4 },
	["Silver"] = { PriceMultiply = 1.6 },
	["Electric"] = { PriceMultiply = 1.45 },
	["Heavenly"] = { PriceMultiply = 6 },
	["Sleet"] = { PriceMultiply = 2.4 },
	["Yellow"] = { PriceMultiply = 1 },
	["Greedy"] = { PriceMultiply = 4 },
	["Ghastly"] = { PriceMultiply = 2 },
}
