return {
	"Abyssal Boots",
	"Abyssal Helmet",
	"Abyssal Plate",
	"Adventurer's Bow",
	"Agility Potion",
	"Amber Lantern",
	"Amethyst Lantern",
	"Anchor",
	"Ancient Demon Skull",
	"Antidote Potion",
	"Apple",
	"Apple Pie",
	"Arachnids Bite",
	"Arachnids Hat",
	"Arachnids Pants",
	"Arachnids Robes",
	"Arachnids Shot",
	"Arachnids Staff",
	"Assassin's Boots",
	"Assassin's Cloak",
	"Assassin's Hood",
	"Backpack",
	"Basilisk Blade",
	"Basilisk Greatblade",
	"Bastion Boots",
	"Bastion Helmet",
	"Bastion Plate",
	"Bear Bow",
	"Bear Claws",
	"Bear Sword",
	"Beastman Bow",
	"Beastman Sword",
	"Black Omen",
	"Black Ooze Slime Boots",
	"Blessed Band",
	"Bulky Leather Boots",
	"Butcher Knife",
	"Caster's Ring",
	"Champion Belt",
	"Champion Cape",
	"Champion Cleaver",
	"Cleanse Potion",
	"Cloak of Rat Speed",
	"Cold Protection Potion",
	"Conjured Apple Pie",
	"Conjured Meat",
	"Conjured Mineral Water",
	"Conjured Seasoned Meat",
	"Conjured Sparkling Water",
	"Conjured Water",
	"Cooked Apple",
	"Cooked Bass",
	"Cooked Bear Meat",
	"Cooked Black Bass",
	"Cooked Blue Jellyfish",
	"Cooked Boar Meat",
	"Cooked Clownfish",
	"Cooked Crocodile Meat",
	"Cooked Deer Meat",
	"Cooked Dolphin",
	"Cooked Fish",
	"Cooked Goblin Meat",
	"Cooked Mackeral",
	"Cooked Meat",
	"Cooked Mudfish",
	"Cooked Panther Meat",
	"Cooked Piranha",
	"Cooked Prime Meat",
	"Cooked Pufferfish",
	"Cooked Red Jellyfish",
	"Cooked Salmon",
	"Cooked Serpent Meat",
	"Cooked Stingray",
	"Cooked Storm Clapper",
	"Cooked Sunfish",
	"Cooked Wolf Meat",
	"Cooked Wraithfin",
	"Cooked Yellow Jellyfish",
	"Copper Axe",
	"Copper Boots",
	"Copper Chestplate",
	"Copper Dagger",
	"Copper Greatsword",
	"Copper Helmet",
	"Copper Pickaxe",
	"Copper Shield",
	"Copper Sickle",
	"Copper Sword",
	"Cotton Bag",
	"Cotton Gi",
	"Cotton Gi Pants",
	"Cotton Hat",
	"Cotton Headband",
	"Cotton Pants",
	"Cotton Robes",
	"Crab Boots",
	"Crab Bow",
	"Crab Carapace",
	"Croc Slicer",
	"DK Shades",
	"Demon Circlet",
	"Demon Gauntlets",
	"Demonic Greatsword",
	"Devil's Apple",
	"Dire Bear Boots",
	"Dire Bear Bow",
	"Dire Bear Dagger",
	"Dire Bear Garbs",
	"Dire Bear Gloves",
	"Dire Bear Hat",
	"Dire Bear Sword",
	"Divine Concord",
	"Doom Band",
	"Doom Carver",
	"Doom Cloak",
	"Drogar's Chestplate",
	"Ectoplasmic Cloak",
	"Ectoplasmic Pants",
	"Ectoplasmic Robes",
	"Edge Wing",
	"Elder Boots",
	"Elder Chest",
	"Elder Gauntlets",
	"Elder Mask",
	"Elder Ring",
	"Elder Shield",
	"Elderwood Bow",
	"Elderwood Staff",
	"Elysian Dagger",
	"Emberfrost Ring",
	"Fiendclaw Blade",
	"Fist",
	"Flame Signet",
	"Flame Stone Ring",
	"Flax Gi",
	"Flax Gi Pants",
	"Flax Hat",
	"Flax Headband",
	"Flax Pants",
	"Flax Robes",
	"Flesh Ripper",
	"Focus Ring",
	"Forsworn Boots",
	"Forsworn Mask",
	"Forsworn Vest",
	"Fresh Water",
	"Gauntlets of Devotion",
	"Giant Slayer's Ring",
	"Goblin Armor",
	"God Apple",
	"Greater Agility Potion",
	"Greater Health Potion",
	"Greater Mana Potion",
	"Greater Strength Potion",
	"Hallowed Bow",
	"Health Potion",
	"Hearty Tonic",
	"Heat Protection Potion",
	"Heavy Leather Boots",
	"Heavy Leather Gloves",
	"Heavy Leather Mask",
	"Heavy Leather Vest",
	"Hellfang Gi",
	"Hellfang Gi Pants",
	"Hellfang Headband",
	"Hellpiercer",
	"Hex Ring",
	"Hodor's War Helmet",
	"Holy Signet",
	"Holy Stone Ring",
	"Hunting Bow",
	"Imp Staff",
	"Infernal Covenant",
	"Invisibility Potion",
	"Iron Axe",
	"Iron Boots",
	"Iron Chestplate",
	"Iron Dagger",
	"Iron Fishing Rod",
	"Iron Greataxe",
	"Iron Greatsword",
	"Iron Helmet",
	"Iron Pickaxe",
	"Iron Shield",
	"Iron Sickle",
	"Iron Spear",
	"Iron Sword",
	"Judicator",
	"Katana",
	"Kilineiram",
	"King Slime Staff",
	"Klinge",
	"Knuckle Dusters",
	"Lakewood Bow",
	"Lakewood Staff",
	"Landing Tonic",
	"Lantern",
	"Lanza's Merit",
	"Lesser Agility Potion",
	"Lesser Health Potion",
	"Lesser Mana Potion",
	"Lesser Strength Potion",
	"Light Leather Boots",
	"Light Leather Gloves",
	"Light Leather Mask",
	"Light Leather Vest",
	"Lilyleaf Bag",
	"Lilyleaf Gi",
	"Lilyleaf Gi Pants",
	"Lilyleaf Hat",
	"Lilyleaf Headband",
	"Lilyleaf Pants",
	"Lilyleaf Robes",
	"Lions Claw",
	"Lucky Ring",
	"Maelis's Potion",
	"Maelis's Ring",
	"Magicians Book",
	"Magicians Sash",
	"Malefic Hat",
	"Malefic Pants",
	"Malefic Robes",
	"Mana Potion",
	"Mandrake King's Crown",
	"Mandrake Root",
	"Medium Leather Boots",
	"Medium Leather Gloves",
	"Medium Leather Mask",
	"Medium Leather Vest",
	"Night Piercer",
	"Oak Bow",
	"Oak Staff",
	"Panther Claws",
	"Paraglider",
	"Philosophers Ring",
	"Piercing Band",
	"Piercing Magic Band",
	"Pine Bow",
	"Pine Staff",
	"Platinum Axe",
	"Platinum Boots",
	"Platinum Chestplate",
	"Platinum Dagger",
	"Platinum Greatsword",
	"Platinum Helmet",
	"Platinum Pickaxe",
	"Platinum Shield",
	"Platinum Sickle",
	"Platinum Sword",
	"Poisonbite Ring",
	"Primordial Ring",
	"Profaned Gauntlets",
	"Quarter Staff",
	"Ragnarok",
	"Rat Cape",
	"Rat Carver",
	"Regen Potion",
	"Ring of Resistance",
	"Ring of Second Eye",
	"Ring of Vitality",
	"Rocky Mountain Tonic",
	"Root Staff",
	"Ruby Lantern",
	"Sage Ring",
	"Salmon",
	"Sanctified Hat",
	"Sanctified Pants",
	"Sanctified Robes",
	"Sand Shooter",
	"Sanguine Blade",
	"Sapphire Lantern",
	"Scroll: Chain Lightning",
	"Scroll: Detoxification",
	"Scroll: Divine Smite",
	"Scroll: Earth Pillar",
	"Scroll: Earth Wall",
	"Scroll: Enlighten",
	"Scroll: Fireball",
	"Scroll: Flame Pillar",
	"Scroll: Flame Slice",
	"Scroll: Flamethrower",
	"Scroll: Heal",
	"Scroll: Holy Light",
	"Scroll: Ignite",
	"Scroll: Lesser Heal",
	"Scroll: Plague Breath",
	"Scroll: Plague of Rats",
	"Scroll: Rock Bullet",
	"Scroll: Self Heal",
	"Scroll: Smite",
	"Scroll: Stone Cannon",
	"Scroll: Storm Sphere",
	"Scroll: Summoning Portal",
	"Scroll: Thunder Strike",
	"Scroll: Tornado",
	"Scroll: Water Cannon",
	"Scroll: Waterball",
	"Scroll: Waterfall",
	"Scroll: Wind Bind",
	"Scroll: Wind Blast",
	"Scroll: Wind Gust",
	"Scroll: Wind Slice",
	"Seraph Gi",
	"Seraph Gi Pants",
	"Seraph Headband",
	"Serpent Dagger",
	"Shadow Band",
	"Sharp Necklace",
	"Shield God's Ring",
	"Silk Gi",
	"Silk Gi Pants",
	"Silk Hat",
	"Silk Headband",
	"Silk Pants",
	"Silk Robes",
	"Silver Axe",
	"Silver Boots",
	"Silver Chestplate",
	"Silver Dagger",
	"Silver Greatsword",
	"Silver Helmet",
	"Silver Pickaxe",
	"Silver Shield",
	"Silver Sickle",
	"Silver Sword",
	"Simple Dagger",
	"Simple Sword",
	"Sinbrand",
	"Skill Book: Dimensional Slash",
	"Skill Book: Dual Weapons",
	"Skill Book: Moon Cutting",
	"Skill Book: Shadow Knives",
	"Slayer Tonic",
	"Slime Bag",
	"Slime Boots",
	"Slime Crown",
	"Slime Shield",
	"Slime Staff",
	"Solarius",
	"Sorcerer's Ring",
	"Spectre Dagger",
	"Spectre Staff",
	"Spell Signet",
	"Spell Stone Ring",
	"Spider Leg Bow",
	"Spider Staff",
	"Spiders Claw",
	"Splinted Club",
	"Splinted Dagger",
	"Splinted Shield",
	"Splinted Spear",
	"St. Saven's Retribution",
	"Stalker Boots",
	"Stalker Hood",
	"Stalker Vest",
	"Straw Hat",
	"Strength Potion",
	"Suveria's Potion",
	"Suveria's Ring",
	"Suveria's Runeblade",
	"Swamp Goulash",
	"Swift Band",
	"Thick Leather Boots",
	"Thick Leather Gloves",
	"Thick Leather Mask",
	"Thick Leather Vest",
	"Thieves Ring",
	"Thieves Sash",
	"Tiki Mask",
	"Troll Tusk Bow",
	"Troll's Stone Column",
	"Turtle Shell",
	"Tusken Blade",
	"Tuskhorn Bow",
	"Unholy Para",
	"Vampiric Ring",
	"Vangar's Coat",
	"Vangar's Scarf",
	"Void Piercer",
	"War Troll Boots",
	"War Troll Chestplate",
	"War Troll Helmet",
	"Warrior's Ring",
	"Warriors Sash",
	"Winged Boots",
	"Winged Helmet",
	"Wolf Tooth Dagger",
	"Wolve's Blood",
	"Wood Fishing Rod",
	"Worm",
}
